import './globals.css'
import { Playfair_Display, Public_Sans } from 'next/font/google'

export const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
})

export const publicSans = Public_Sans({
  subsets: ['latin'],
  variable: '--font-public',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${publicSans.variable} ${playfair.variable}`}>{children}</body>
    </html>
  )
}
